{{- if .Values.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "omnicare.backend.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnicare.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.backend.autoscaling.enabled }}
  minAvailable: {{ max 1 (sub .Values.backend.autoscaling.minReplicas 1) }}
  {{- else }}
  minAvailable: {{ max 1 (sub .Values.backend.replicaCount 1) }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "omnicare.backend.selectorLabels" . | nindent 6 }}
{{- end }}