{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnicare.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnicare.backend.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "omnicare.backend.selectorLabels" . | nindent 4 }}
{{- end }}