{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnicare.backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnicare.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.secrets.JWT_SECRET }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.MEDPLUM_CLIENT_ID }}
  MEDPLUM_CLIENT_ID: {{ .Values.backend.secrets.MEDPLUM_CLIENT_ID | b64enc | quote }}
  {{- else }}
  MEDPLUM_CLIENT_ID: {{ "medplum-client-id" | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.MEDPLUM_CLIENT_SECRET }}
  MEDPLUM_CLIENT_SECRET: {{ .Values.backend.secrets.MEDPLUM_CLIENT_SECRET | b64enc | quote }}
  {{- else }}
  MEDPLUM_CLIENT_SECRET: {{ "medplum-client-secret" | b64enc | quote }}
  {{- end }}
  DATABASE_URL: {{ include "omnicare.databaseUrl" . | b64enc | quote }}
  REDIS_URL: {{ include "omnicare.redisUrl" . | b64enc | quote }}
{{- end }}