{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnicare.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnicare.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "omnicare.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.frontend.service.port }}"
        prometheus.io/path: "/api/metrics"
      labels:
        {{- include "omnicare.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "omnicare.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "omnicare.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: {{ .Values.security.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.security.securityContext.runAsUser }}
        runAsGroup: {{ .Values.security.securityContext.runAsGroup }}
        fsGroup: {{ .Values.security.securityContext.fsGroup }}
      containers:
      - name: frontend
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.service.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.frontend.env.NODE_ENV | quote }}
        - name: PORT
          value: {{ .Values.frontend.env.PORT | quote }}
        - name: HOSTNAME
          value: {{ .Values.frontend.env.HOSTNAME | quote }}
        - name: NEXT_TELEMETRY_DISABLED
          value: {{ .Values.frontend.env.NEXT_TELEMETRY_DISABLED | quote }}
        - name: NEXT_PUBLIC_API_URL
          value: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
        - name: NEXT_PUBLIC_MEDPLUM_BASE_URL
          value: {{ .Values.frontend.env.NEXT_PUBLIC_MEDPLUM_BASE_URL | quote }}
        - name: NEXT_PUBLIC_APP_NAME
          value: {{ .Values.frontend.env.NEXT_PUBLIC_APP_NAME | quote }}
        - name: NEXT_PUBLIC_APP_VERSION
          value: {{ .Values.frontend.env.NEXT_PUBLIC_APP_VERSION | quote }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: nextjs-cache
          mountPath: /app/.next/cache
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
          successThreshold: 1
      volumes:
      - name: tmp
        emptyDir: {}
      - name: nextjs-cache
        emptyDir: {}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}