version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: omnicare_test
      POSTGRES_USER: omnicare
      POSTGRES_PASSWORD: omnicare123
      POSTGRES_EXTENSIONS: "uuid-ossp,pgcrypto,pg_trgm"
    ports:
      - "5433:5432"
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnicare -d omnicare_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --databases 16
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /data

  medplum:
    image: medplum/medplum-server:latest
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://omnicare:omnicare123@postgres:5432/omnicare_test
      REDIS_URL: redis://redis:6379/2
      BASE_URL: http://localhost:8103
      PORT: 8103
    ports:
      - "8103:8103"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8103/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    name: omnicare-test-network