version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: omnicare-test-postgres
    environment:
      POSTGRES_USER: omnicare
      POSTGRES_PASSWORD: omnicare123
      POSTGRES_DB: omnicare_test
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"  # Different port to avoid conflicts with dev DB
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnicare -d omnicare_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - omnicare-test-network

  redis:
    image: redis:7-alpine
    container_name: omnicare-test-redis
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"  # Different port to avoid conflicts with dev Redis
    volumes:
      - test-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - omnicare-test-network

volumes:
  test-postgres-data:
    driver: local
  test-redis-data:
    driver: local

networks:
  omnicare-test-network:
    driver: bridge
    name: omnicare-test-network