"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Permission = exports.UserRole = void 0;
var UserRole;
(function (UserRole) {
    UserRole["PHYSICIAN"] = "physician";
    UserRole["NURSING_STAFF"] = "nursing_staff";
    UserRole["ADMINISTRATIVE_STAFF"] = "administrative_staff";
    UserRole["SYSTEM_ADMINISTRATOR"] = "system_administrator";
    UserRole["PHARMACIST"] = "pharmacist";
    UserRole["LABORATORY_TECHNICIAN"] = "laboratory_technician";
    UserRole["RADIOLOGY_TECHNICIAN"] = "radiology_technician";
    UserRole["PATIENT"] = "patient";
})(UserRole || (exports.UserRole = UserRole = {}));
var Permission;
(function (Permission) {
    Permission["CREATE_CLINICAL_NOTES"] = "create_clinical_notes";
    Permission["EDIT_CLINICAL_NOTES"] = "edit_clinical_notes";
    Permission["VIEW_CLINICAL_NOTES"] = "view_clinical_notes";
    Permission["FINALIZE_CLINICAL_NOTES"] = "finalize_clinical_notes";
    Permission["CREATE_PRESCRIPTIONS"] = "create_prescriptions";
    Permission["MODIFY_PRESCRIPTIONS"] = "modify_prescriptions";
    Permission["VIEW_PRESCRIPTIONS"] = "view_prescriptions";
    Permission["VERIFY_PRESCRIPTIONS"] = "verify_prescriptions";
    Permission["DISPENSE_MEDICATIONS"] = "dispense_medications";
    Permission["VIEW_PATIENT_RECORDS"] = "view_patient_records";
    Permission["EDIT_PATIENT_RECORDS"] = "edit_patient_records";
    Permission["CREATE_PATIENT_RECORDS"] = "create_patient_records";
    Permission["VIEW_PATIENT_DEMOGRAPHICS"] = "view_patient_demographics";
    Permission["EDIT_PATIENT_DEMOGRAPHICS"] = "edit_patient_demographics";
    Permission["CREATE_MEDICAL_ORDERS"] = "create_medical_orders";
    Permission["VIEW_LAB_RESULTS"] = "view_lab_results";
    Permission["ENTER_LAB_RESULTS"] = "enter_lab_results";
    Permission["ACKNOWLEDGE_CRITICAL_RESULTS"] = "acknowledge_critical_results";
    Permission["SCHEDULE_APPOINTMENTS"] = "schedule_appointments";
    Permission["MANAGE_BILLING"] = "manage_billing";
    Permission["PROCESS_INSURANCE"] = "process_insurance";
    Permission["GENERATE_REPORTS"] = "generate_reports";
    Permission["MANAGE_USERS"] = "manage_users";
    Permission["CONFIGURE_SYSTEM"] = "configure_system";
    Permission["VIEW_AUDIT_LOGS"] = "view_audit_logs";
    Permission["MANAGE_SECURITY_SETTINGS"] = "manage_security_settings";
    Permission["PERFORM_IMAGING_STUDIES"] = "perform_imaging_studies";
    Permission["VIEW_IMAGING_RESULTS"] = "view_imaging_results";
    Permission["MANAGE_IMAGING_EQUIPMENT"] = "manage_imaging_equipment";
    Permission["DOCUMENT_VITAL_SIGNS"] = "document_vital_signs";
    Permission["ADMINISTER_MEDICATIONS"] = "administer_medications";
    Permission["DOCUMENT_NURSING_CARE"] = "document_nursing_care";
    Permission["MANAGE_PATIENT_CARE_PLANS"] = "manage_patient_care_plans";
    Permission["VIEW_OWN_RECORDS"] = "view_own_records";
    Permission["REQUEST_APPOINTMENTS"] = "request_appointments";
    Permission["MESSAGE_CARE_TEAM"] = "message_care_team";
    Permission["UPDATE_PERSONAL_INFO"] = "update_personal_info";
})(Permission || (exports.Permission = Permission = {}));
//# sourceMappingURL=auth.types.js.map