# Kubernetes Namespace for OmniCare EMR
apiVersion: v1
kind: Namespace
metadata:
  name: omnicare
  labels:
    name: omnicare
    app.kubernetes.io/name: omnicare-emr
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: omnicare-emr
    environment: production
    compliance: hipaa
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: omnicare-quota
  namespace: omnicare
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
# Limit Range for pods
apiVersion: v1
kind: LimitRange
metadata:
  name: omnicare-limits
  namespace: omnicare
spec:
  limits:
  - default:
      cpu: "500m"
      memory: 512Mi
    defaultRequest:
      cpu: "100m"
      memory: 128Mi
    type: Container
  - max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: "50m"
      memory: 64Mi
    type: Container